### ISSUE TITLE
implement a factor method ?

### ISSUE THREAD

**Issue by fchapoton** [pbelmans/hodge-diamond-cutter#19]
by factoring the polynomial over ZZ and then making diamonds for each factor

not sure if this is pertinent, but this should be easy

**Comment by pbelmans** [comment]
I haven't needed it so far, but it is an interesting suggestion nonetheless. I'll check whether a use case arises.

**Comment by fchapoton** [comment]
not so easy, because it can happen that the polynomial factors,but not the diamond :
```
sage: load("diamond.py")
sage: a=abelian(3)
sage: a.polynomial
x^3*y^3 + 3*x^3*y^2 + 3*x^2*y^3 + 3*x^3*y + 9*x^2*y^2 + 3*x*y^3 + x^3 + 9*x^2*y + 9*x*y^2 + y^3 + 3*x^2 + 9*x*y + 3*y^2 + 3*x + 3*y + 1
sage: a.polynomial.factor()
(y + 1)^3 * (x + 1)^3
```

**Comment by pbelmans** [comment]
Ah yes, good example. It is a nice manifestation of the principle that abelian varieties are fully controlled by what happens in their degree 1.

**Comment by fchapoton** [comment]
why completed ? it still makes sense, even if not easy

**Comment by fchapoton** [comment]
So there is no theoretical answer, something like unique factorisation ? or is this known to fail ?

**Comment by pbelmans** [comment]
Nothing comes to mind, but I could be missing something of course!

The abelian example is also nicely explained by the fact that a power of an elliptic curve is itself an abelian variety. I should've mentioned this before.

So that's what I mean with there are at least 2 meaningful factorisations for `abelian(3)`:
* one into 6 factors, not arising from a smooth projective variety
* one into 3 factors, namely 3 copies of `1+x+y+xy`, the Hodge polynomial of an elliptic curve

**Comment by pbelmans** [comment]
Maybe something useful can be said using https://arxiv.org/abs/1301.0478v3. So first one considers a factorisation in `ZZ[x,y]`, and then considers all partitions of the factors such that the products of the subsets satisfy the conditions in Schreieder's paper.

But is there guaranteed to be a unique one? I'm not sure!

And like I said: I haven't run into a use case for this yet. But it's good to keep this in mind, maybe now that I'm aware of the question I'll realise some use for it.
